export const qair_comms = [
  { code: "CL", name: "CLOTHING" },
  { code: "RWM", name: "RAW MATERIALS" },
  { code: "MED", name: "MEDICINES" },
  { code: "TU", name: "TUNA" },
  { code: "FRU", name: "FRUITS" },
  { code: "SH", name: "SHOES" },
  { code: "BN", name: "BOLTS & NUTS" },
  { code: "GC", name: "GENERAL CARGO" },
  { code: "STY", name: "STYRO (EMPTY)" },
  { code: "MCP", name: "MACHINERY PARTS" },
  { code: "PRA", name: "PRAWN" },
  { code: "LHO", name: "LIVE HUMAN ORGAN" },
  { code: "J1", name: "JAIFI - MANGO" },
  { code: "VIT", name: "VITAMINS" },
  { code: "PE", name: "PERSONAL EFFECTS" },
  { code: "BR", name: "BROCHURES" },
  { code: "VCC", name: "VACCINES" },
  { code: "FEX", name: "FIRE EXTINGUISHER" },
  { code: "CO", name: "COSMETICS" },
  { code: "LI", name: "LIGHTER/MATCHES" },
  { code: "EP", name: "ELECTRICAL PARTS" },
  { code: "BB", name: "BALIKBAYAN BOXES" },
  { code: "AL", name: "ALBUMS" },
  { code: "GR", name: "GROCERIES" },
  { code: "FW", name: "FLOWERS" },
  { code: "DP", name: "DAIRY PRODUCTS" },
  { code: "TL", name: "TOILETRIES" },
  { code: "LA", name: "LIVE ANIMALS (PER HEAD)" },
  { code: "PA", name: "PAINT/VARNISH" },
  { code: "CA", name: "COMPUTER & ACCESSORIES" },
  { code: "CM", name: "CAMPAIGN MATERIALS" },
  { code: "ESP", name: "ESPARAGUS" },
  { code: "EL", name: "ELECTRONICS" },
  { code: "LG", name: "LEATHER GOODS" },
  { code: "NP", name: "NEWSPAPERS" },
  { code: "CE", name: "COMMUNICATION EQUIPMENT" },
  { code: "GAR", name: "GARMENTS" },
  { code: "HR", name: "HUMAN REMAIN" },
  { code: "CP", name: "COMPUTERS PARTS" },
  { code: "POD", name: "POD SERVICE CARGO" },
  { code: "DF", name: "DRIED FISH" },
  { code: "SS", name: "SCHOOL SUPPLIES" },
  { code: "DGJW", name: "DANGEROUS GOODS WITH JACK-WRAP" },
  { code: "PF", name: "PERFUMES" },
  { code: "PTG", name: "PAINTINGS" },
  { code: "FIN", name: "FINGERLINGS" },
  { code: "LFC", name: "FIGHTING COCKS (PER HEAD)" },
  { code: "SSB", name: "SUPER SAVER BOX" },
  { code: "DO", name: "DOG" },
  { code: "OS", name: "OFFICE SUPPLIES" },
  { code: "PI", name: "PROMO ITEMS" },
  { code: "CT", name: "CAT" },
  { code: "PK", name: "PACKAGING MATERIALS" },
  { code: "BI", name: "BICYCLE/BICYCLE PARTS" },
  { code: "SW", name: "SEAWEEDS" },
  { code: "SP", name: "SPARE PARTS" },
  { code: "HA", name: "HANDICRAFTS" },
  { code: "CST", name: "CASSETTE TAPES" },
  { code: "EX", name: "EXPLOSIVES" },
  { code: "LAB", name: "LIVE ANIMALS (PER BOX)" },
  { code: "JE", name: "JEWELRIES" },
  { code: "HE", name: "HATCHING EGGS" },
  { code: "FU", name: "FURNITURES" },
  { code: "BP", name: "BALIKBAYAN PERAC" },
  { code: "TEX", name: "TEXTILE" },
  { code: "MG", name: "MAGAZINES" },
  { code: "FO", name: "FORMS" },
  { code: "GLW", name: "GLASS WARES" },
  { code: "JW", name: "JACK-WRAP" },
  { code: "LTK", name: "LITTLE TIKES" },
  { code: "RP", name: "RUBBER PRODUCTS" },
  { code: "TOY", name: "TOYS" },
  { code: "PG", name: "PERISHABLE GOODS" },
  { code: "MP", name: "MARINE PRODUCTS" },
  { code: "MO", name: "MANGO" },
  { code: "NONDOC", name: "Non-Document" },
  { code: "TO", name: "TOBACCO/TOBACCO PRODUCTS" },
  { code: "POST", name: "POSTERS, TRAILERS, ADS" },
  { code: "OG", name: "OPTICAL GOODS" },
  { code: "PL", name: "PLANTS" },
  { code: "CC", name: "CANDIES/CHOCOLATES" },
  { code: "PP", name: "PHARMA PRODUCTS" },
  { code: "ELI", name: "ELECTRICAL INSTRUMENTS" },
  { code: "VP", name: "VETERINARY PRODUCTS" },
  { code: "FC", name: "FIGHTING COCKS" },
  { code: "KD", name: "KD CARTONS" },
  { code: "FL", name: "FLOUR/BAKERY PRODUCTS" },
  { code: "GM", name: "GEN MERCHANDISE" },
  { code: "ET", name: "EMPTY TANK (OXYGEN, LPG)" },
  { code: "CELJW", name: "CELLPHONE WITH JACK-WRAP" },
  { code: "CMF", name: "CINEMATIC FILMS" },
  { code: "BOK", name: "BOOKS" },
  { code: "RM", name: "RADIOACTIVE MATERIALS" },
  { code: "FILM", name: "FILMS" },
  { code: "AM", name: "AMMUNITION" },
  { code: "DI", name: "DRY ICE" },
  { code: "MB", name: "MAILBAGS(PHILPOST)" },
  { code: "SPS", name: "SHELL PRODUCTS" },
  { code: "CER", name: "CERAMICS" },
  { code: "DOC", name: "DOCUMENT" },
  { code: "CBE", name: "CABLE EQUIPMENT" },
  { code: "WI", name: "WINES" },
  { code: "PCM", name: "PROCESSED MEAT" },
  { code: "LUB", name: "LUBRICANT / GREASE / PETROLEUM PRODS" },
  { code: "GL", name: "GLASS" },
  { code: "PGJW", name: "PERISHABLE WITH JACK-WRAP" },
  { code: "FG", name: "Fragile" },
  { code: "CG", name: "CANNED GOODS" },
  { code: "PRM", name: "PRINTED MATTERS" },
  { code: "FE", name: "FERTILIZER" },
  { code: "CH", name: "CHEMICALS" },
  { code: "POR", name: "PORCELAIN" },
  { code: "FV", name: "FRUITS & VEGETABLES" },
  { code: "EC", name: "EMPTY CARTONS" },
  { code: "BTR", name: "BUTTER" },
  { code: "CON", name: "CONTRACEPTIVES" },
  { code: "DAYC", name: "DAY OLD CHICKS" },
  { code: "DG", name: "Dangerous Goods" },
].sort((a, b) => {
  let fa = a.name,
    fb = b.name;

  if (fa < fb) {
    return -1;
  }
  if (fa > fb) {
    return 1;
  }
  return 0;
});
